### ISSUE TITLE
"Names consisting only of numbers are not supported" error

### ISSUE THREAD

**Issue by fsih** [scratchfoundation/paper.js#13]
`<g id="1" transform="translate(46.000000, 37.000000)" fill-rule="nonzero">`
SVGs with IDs consisting of only numbers can't be imported, such as one with the above substring.
That seems quite brittle. By default some vector applications and SVG optimizers give groups a number.
from @thisandagain

**Comment by fsih** [comment]
svg and html both specify that id must start with a non number https://www.w3.org/TR/SVG/struct.html#Core.attrib points to https://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameStartChar which excludes numbers as valid NameStartChar

id="1" is not legal
from @gnarf

**Comment by gnarf** [comment]
you can run it through the svgo cleanupIDs transform with prefixs: https://github.com/svg/svgo/blob/master/plugins/cleanupIDs.js

thats how i did it in my custom-svg-loader for loading icons in a recent webpack thing - but it's general approach used in that file would help you parse it yourself too I think, first pass is look for and replace all id="...." with a generated id, then look at all attributes for `#usedId` and replace with `#newGeneratedId`

**Comment by paulkaplan** [comment]
This is another project that fails for the same reason https://github.com/LLK/scratch-gui/issues/2801

**Comment by rschamp** [comment]
We should do something like @gnarf suggests in LLK/scratch-svg-renderer

**Comment by fsih** [comment]
@rschamp @thisandagain we talked about having Bocoup take this bug before it was assigned to me. Should it be assigned to me?

**Comment by fsih** [comment]
Moved to LLK/scratch-svg-renderer#53
